Music-Store/Controllers/LanguagesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Music_Store.Data;
using Music_Store.Models;

namespace Music_Store.Controllers
{
    [Authorize]
    public class LanguageController : Controller
    {
        private readonly MusicDataContext _db;
        public LanguageController(MusicDataContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            List<LanguageTbl> list = _db.Languages.ToList();
            return View(list);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(LanguageTbl language)
        {
            if (ModelState.IsValid)
            {
                _db.Languages.Add(language);
                _db.SaveChanges();
                TempData["Success"] = "Language Created Successfully";
                return RedirectToAction("Index");
            }
            return View(language);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            LanguageTbl? language1 = _db.Languages.Find(id);
            if (language1 == null)
            {
                return NotFound();
            }
            return View(language1);
        }
        [HttpPost]
        public IActionResult Edit(LanguageTbl language)
        {

            if (ModelState.IsValid)
            {
                _db.Languages.Update(language);
                _db.SaveChanges();
                TempData["Info"] = "Language Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(language);
        }

        public IActionResult Delete(int? id)
        {
            LanguageTbl? languages = _db.Languages.Find(id);
            if (languages == null)
            {
                return NotFound();
            }
            return View(languages);
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            LanguageTbl? language = _db.Languages.Find(id);
            if (language == null)
            {
                return NotFound();
            }
            _db.Remove(language);
            _db.SaveChanges();
            TempData["Error"] = "Language Deleted Successfully";
            return RedirectToAction("Index");
        }
    }
}

Music-Store/Views/Language/Create.cshtml
@model LanguageTbl
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class=" text-primary">Add Language</h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            @* <input asp-for="LanguageId" hidden/> *@
            <label asp-for="LanguageName" class="p-0"></label>
            <input asp-for="LanguageName" class="form-control" />
            <span asp-validation-for="LanguageName" class="text-danger"></span>
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-success form-control">Create</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Language" asp-action="Index" class="btn btn-secondary">Back</a>
            </div>
        </div>
    </div>
</form>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Music-Store/Views/Language/Delete.cshtml
@model LanguageTbl
<form method="post">

    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class=" text-primary">Delete Languages</h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <input asp-for="LanguageId" hidden />
            <label asp-for="LanguageName" class="p-0"></label>
            <input asp-for="LanguageName" class="form-control" disabled />

        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-danger form-control">Delete</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Language" asp-action="Index" class="btn btn-secondary">Back</a>
            </div>
        </div>
    </div>
</form>

Music-Store/Views/Language/Edit.cshtml
@model LanguageTbl
<form method="post">

    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class=" text-primary">Update Language</h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <input asp-for="LanguageId" hidden />
            <label asp-for="LanguageName" class="p-0"></label>
            <input asp-for="LanguageName" class="form-control" />
            <span asp-validation-for="LanguageName" class="text-danger"></span>
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Update</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Language" asp-action="Index" class="btn btn-secondary">Back</a>
            </div>
        </div>
    </div>
</form>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Music-Store/Views/Language/Index.cshtml
@model List<LanguageTbl>

<div class="container">
    <div class="row pt-4 pb-3 offset-md-1">
        <div class="col-6">
            <h2 class="text-primary">Language List</h2>
        </div>
        <div class="col-6  text-end ">
            <a asp-controller="Language" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>  Add New Language
            </a>
        </div>
        <div class="row py-2">
            <table class="table table-borderless table-responsive table-striped">
                <thead>
                    <tr>
                        <th>Language Name</th>
                        <th></th>
                    </tr>

                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.LanguageName</td>
                            <td>
                                <div class="btn btn-group float-end" role="group">
                                    <a asp-controller="Language" asp-action="Edit" asp-route-id="@item.LanguageId" class="btn btn-primary"><i class="bi bi-pencil-square"></i>Edit</a>
                                    <a asp-controller="Language" asp-action="Delete" asp-route-id="@item.LanguageId" class="btn btn-danger">
                                        <i class="bi bi-trash"></i> Delete
                                    </a>
                                </div>
                            </td>

                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>