Music-Store/Controllers/AlbumController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Music_Store.Data;
using Music_Store.Models;
using System.Linq;
using System.Linq.Expressions;

namespace Music_Store.Controllers
{
    
    
    public class AlbumController : Controller
    {
        private readonly MusicDataContext _music;

        public AlbumController(MusicDataContext music)
        {
            _music = music;
        }
        public IActionResult Index()
        {
            List<AlbumTbl> albums = _music.Albums.ToList();
           

            return View(albums);
        }

        public IActionResult AlbumShow()
        {
            
        List<AlbumTbl> album = _music.Albums.
                Include(a=>a.SongTbls).ThenInclude(b=>b.Singer)
                .ToList();
              
            return View(album);
        }

        public IActionResult SongList(int? id)
        {
           if(id.Value == null || id== 0)
            {
                return NotFound();
            }

         var album = _music.Songs.Where(x => x.AlbumId ==id).
                Include(a=>a.Album).
                Include(s=>s.Singer).
                Include(l=>l.Language).
               
                ToList();
              if (album == null)
                {
                   return NotFound();
                }

            return View(album);

        }

        [Authorize]
        public IActionResult Create()
        {
         
            return View();
        }
        [HttpPost]
        public IActionResult Create(AlbumTbl album)
        {
            if (ModelState.IsValid)
            {
                _music.Albums.Add(album);
                _music.SaveChanges();
                TempData["Success"] = "Album Created Successfully";
                return RedirectToAction("Index");
            }
            return View(album);
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {

                return NotFound();
            }
            AlbumTbl? album = _music.Albums.Find(id);
            if (album == null)
            {
                return NotFound();

            }

                  

            return View(album);
        }
        [HttpPost]
        public IActionResult Edit(AlbumTbl album)
        {
            if (ModelState.IsValid)
            {
                _music.Albums.Update(album);
                _music.SaveChanges();
                TempData["Info"] = "Album Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(album);
        }

        public IActionResult Delete(int? id)
        {
            AlbumTbl? album = _music.Albums.Find(id);
            if (album == null)
            {
                return NotFound();
            }
            return View(album);
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            AlbumTbl? album1 = _music.Albums.Find(id);
            if (album1 == null)
            {
                return NotFound();
            }
            _music.Remove(album1);
            _music.SaveChanges();
            TempData["Error"] = "Album Deleted Successfully";
            return RedirectToAction("Index");
        }
    }
}

Music-Store/Controllers/GenreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Music_Store.Data;
using Music_Store.Models;

namespace Music_Store.Controllers
{
    [Authorize]
    public class GenreController : Controller
    {
        private readonly MusicDataContext _music;
        public GenreController(MusicDataContext music)
        {
            _music = music;
        }
        public IActionResult Index()
        {
            List<GenreTbl> genre = _music.Genres.ToList();
            return View(genre);
        }
        public IActionResult Create()
        {
            return View();
        }
        //public IActionResult searchsonng( String name)

        //{
        //    List<SongTbl> temp= _music.Songs.Where(x=>x.SongName.Contains(name)).ToList();
           
        //    return View();
        //}

        [HttpPost]
        public IActionResult Create(GenreTbl genres)
        {
            if (ModelState.IsValid)
            {
                _music.Genres.Add(genres);
                _music.SaveChanges();
                TempData["Success"] = "Genre Created Successfully";
                return RedirectToAction("Index");
            }
            return View(genres);
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {

                return NotFound();
            }
            GenreTbl? genre = _music.Genres.Find(id);
            if (genre == null)
            {
                return NotFound();

            }
            return View(genre);
        }
        [HttpPost]
        public IActionResult Edit(GenreTbl genre)
        {
            if (ModelState.IsValid)
            {
                _music.Genres.Update(genre);
                _music.SaveChanges();
                TempData["Info"] = "Genre Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(genre);
        }

        public IActionResult Delete(int? id)
        {
            GenreTbl? genre = _music.Genres.Find(id);
            if (genre == null)
            {

                return NotFound();
            }
            return View(genre);
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            GenreTbl? genre = _music.Genres.Find(id);
            if (genre == null)
            {
                return NotFound();
            }
            _music.Remove(genre);
            _music.SaveChanges();
            TempData["Error"] = "Genre Deleted Successfully";
            return RedirectToAction("Index");
        }




    }
}

Music-Store/Controllers/SongController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Music_Store.Data;
using Music_Store.Models;

namespace Music_Store.Controllers
{
    [Authorize]
    public class SongController : Controller
    {
        private readonly MusicDataContext _db;
        private readonly IWebHostEnvironment _webhostenvironment;
        public SongController(MusicDataContext db, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _webhostenvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<SongTbl> list = _db.Songs.
                Include(g => g.Genre)
               .Include(c => c.Album)
               .Include(a => a.Singer)
               .Include(b => b.Language)
                .ToList();
            return View(list);
        }

        public IActionResult Create()
        {
            IEnumerable<SelectListItem> genreList = _db.Genres.ToList().Select(u => new SelectListItem
            {
                Text = u.GenreName,
                Value = u.GenreId.ToString()
            });
            ViewBag.GenreList = genreList;

            IEnumerable<SelectListItem> albumList = _db.Albums.ToList().Select(u => new SelectListItem
            {
                Text = u.AlbumTitle,
                Value = u.AlbumId.ToString()
            });
            ViewBag.AlbumList = albumList;

            IEnumerable<SelectListItem> singerList = _db.Singers.ToList().Select(u => new SelectListItem
            {
                Text = u.SingerName,
                Value = u.SingerId.ToString()
            });
            ViewBag.SingerList = singerList;

            IEnumerable<SelectListItem> languageList = _db.Languages.ToList().Select(u => new SelectListItem
            {
                Text = u.LanguageName,
                Value = u.LanguageId.ToString()
            });
            ViewBag.LanguageList = languageList;

            return View();
        }
        [HttpPost]
        public IActionResult Create(SongTbl songs, IFormFile? file, IFormFile? file1)
        {
            if(ModelState.IsValid)
            {
                string wwwRootPath = _webhostenvironment.WebRootPath;
                if (file!= null)
                {
                    string filename = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string imagePath = Path.Combine(wwwRootPath, @"Images/Songs");
                    using (var fileStream = new FileStream(Path.Combine(imagePath, filename), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                        songs.SongPicture = @"\Images\Songs\" + filename;
                }
                if(file1 != null)
                {
                    string filename = Guid.NewGuid().ToString() + Path.GetExtension(file1.FileName);
                    string musicPath = Path.Combine(wwwRootPath, @"music");
                    using (var fileStream = new FileStream(Path.Combine(musicPath, filename), FileMode.Create))
                    {
                        file1.CopyTo(fileStream);
                    }
                    songs.SongFilepath = @"\music\" + filename;
                }
                    _db.Songs.Add(songs);
                _db.SaveChanges();
                TempData["Success"] = "Song Created Successfully";
                return RedirectToAction("Index");   
            }
            return View(songs);
        }

        public IActionResult Edit(int? id)
        {
            if(id == null|| id == 0)
            {
                return NotFound();
            }
            IEnumerable<SelectListItem> genreList = _db.Genres.ToList().Select(u => new SelectListItem
            {
                Text = u.GenreName,
                Value = u.GenreId.ToString()
            });
            ViewBag.GenreList = genreList;

            IEnumerable<SelectListItem> albumList = _db.Albums.ToList().Select(u => new SelectListItem
            {
                Text = u.AlbumTitle,
                Value = u.AlbumId.ToString()
            });
            ViewBag.AlbumList = albumList;

            IEnumerable<SelectListItem> singerList = _db.Singers.ToList().Select(u => new SelectListItem
            {
                Text = u.SingerName,
                Value = u.SingerId.ToString()
            });
            ViewBag.SingerList = singerList;

            IEnumerable<SelectListItem> languageList = _db.Languages.ToList().Select(u => new SelectListItem
            {
                Text = u.LanguageName,
                Value = u.LanguageId.ToString()
            });
            ViewBag.LanguageList = languageList;

            SongTbl? songs = _db.Songs.Find(id);
            if(songs == null)
            {
                return NotFound();
            }
            return View(songs);


        }

        [HttpPost]
        public IActionResult Edit(SongTbl songs, IFormFile? file, IFormFile? file1)
        {
            if(ModelState.IsValid)
            {
                string wwwroothpath = _webhostenvironment.WebRootPath;
                if (file != null)
                {
                    string filename = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string imagepath = Path.Combine(wwwroothpath, @"Images/Songs");
                    if (!string.IsNullOrEmpty(songs.SongPicture))
                    {
                        var oldImagePath = Path.Combine(wwwroothpath, songs.SongPicture.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }
                    using (var filestream = new FileStream(Path.Combine(imagepath, filename), FileMode.Create))
                    {
                        file.CopyTo(filestream);
                    }
                    songs.SongPicture = @"\Images\Songs\" + filename;
                }
                // for music update

                if (file1 != null)
                {
                    string filename = Guid.NewGuid().ToString() + Path.GetExtension(file1.FileName);
                    string imagePath = Path.Combine(wwwroothpath, @"music");
                    if (!string.IsNullOrEmpty(songs.SongFilepath))
                    {
                        var oldSongPath = Path.Combine(wwwroothpath, songs.SongFilepath.TrimStart('\\'));
                        if (System.IO.File.Exists(oldSongPath))
                        {
                            System.IO.File.Delete(oldSongPath);
                        }
                    }
                    using (var filestream = new FileStream(Path.Combine(imagePath, filename), FileMode.Create))
                    {
                        file1.CopyTo(filestream);
                    }
                    songs.SongFilepath= @"\music\" + filename;
                }

                var objFromDb = _db.Songs.FirstOrDefault(u => u.SongId == songs.SongId);
                if (objFromDb != null)
                {
                    objFromDb.SongId = songs.SongId;
                    objFromDb.SongName = songs.SongName;
                    objFromDb.SongDescription = songs.SongDescription;
                    objFromDb.SongRelease = songs.SongRelease;
                    objFromDb.AlbumId = songs.AlbumId;
                    objFromDb.GenreId = songs.GenreId;  
                    objFromDb.LanguageId = songs.LanguageId;    
                    objFromDb.SingerId = songs.SingerId;
                    if (songs.SongPicture != null)
                    {
                        objFromDb.SongPicture = songs.SongPicture;
                    }
                   else if(songs.SongFilepath != null)
                    {
                        objFromDb.SongFilepath = songs.SongFilepath;
                    }
                   
                    _db.SaveChanges();
                    TempData["Info"] = "Song Updated Successfully";
                }
                return RedirectToAction("Index");
            }
            return View(songs);
        }

        public IActionResult Delete(int? id)
        {
            if(id== null || id == 0)
            {
                return NotFound();
            }
            SongTbl? songs = _db.Songs.Find(id);
            _db.Songs.Include(a => a.Genre)
                     .Include(b => b.Album)
                     .Include(a => a.Language)
                     .Include(c => c.Singer).ToList();
                
            if(songs == null)
            {
                return NotFound();
            }
            return View(songs);
            
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeleteSongs(int? id)
        {
            SongTbl? songs = _db.Songs.Find(id);
            if(songs == null)
            {
                return NotFound();
            }
            _db.Remove(songs);
            _db.SaveChanges();
            TempData["Error"] = "Song Deleted Successfully";
            return RedirectToAction("Index");
        }
        }

    }

Music-Store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Music_Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Music-Store.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">  

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Music_Store</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Album" asp-action="AlbumShow">Album</a>
                        </li>
                        @if (User.IsInRole("Admin")|| User.Identity.IsAuthenticated) {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Management
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="Singer" asp-action="Index">Singer</a>
                                    </li>

                                    <li>
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="Song" asp-action="Index">Songs</a>
                                    </li>

                                    <li >
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="Album" asp-action="Index">Albums</a>
                                    </li>


                                    <li>
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="Genre" asp-action="Index">Genres</a>
                                    </li>

                                    <li>
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="Language" asp-action="Index">Languages</a>
                                    </li>

                                    @* <li><hr class="dropdown-divider"></li> *@

                                </ul>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-tem">
                            <div class=" p-0 justify-content-end">

                                <form asp-asp-controller="Song" asp-action="Index">
                                   <div class="input-group mb3">
                                        <input type="text" id="term" class="btn btn-outline-primary" name="term" placeholder="Search here !" aria-label="" aria-describedby="basic-addon1" />
                                       <div class="input-group-append">
                                         <button class="btn btn-outline-primary" type="submit">Search</button>  
                                       </div>
                                   </div>
                                    
                                  
                                </form>
                            </div>
                        </li>
                    </ul>
                    <Partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
        <Partial name="_Notifications"/>
       
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="text-align:center">
             made with love by- saamoo
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
   <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Music-Store/Views/Shared/_Notifications.cshtml
@if(TempData["Success"]!=null){

   <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    
    <script type="text/javascript">
        toastr.success('@TempData["Success"]');

    </script>
}


@if(TempData["Info"]!=null){

   <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    
    <script type="text/javascript">
        toastr.info('@TempData["Info"]');

    </script>
}

@if (TempData["Error"] != null)
{

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.error('@TempData["Error"]');

    </script>
}