Music-Store/Controllers/SingerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Music_Store.Data;
using Music_Store.Models;


namespace Music_Store.Controllers
{
    [Authorize]
    public class SingerController : Controller
    {

        private readonly MusicDataContext _music;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public SingerController(MusicDataContext music, IWebHostEnvironment webHostEnvironment)
        {
            _music = music;
            _webHostEnvironment = webHostEnvironment;

        }
        public IActionResult Index()
        {
            IEnumerable<SingerTbl> singer = _music.Singers.ToList();
            return View(singer);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(SingerTbl singer, IFormFile file)
        {

            if (ModelState.IsValid)
            {

                

                string wwwroothpath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string filename = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string imagepath = Path.Combine(wwwroothpath, @"Images/Singer");
                    using (var filestream = new FileStream(Path.Combine(imagepath, filename), FileMode.Create))
                    {
                        file.CopyTo(filestream);
                    }
                    singer.ProfilePicture = @"\Images\Singer\" + filename;
                }
                _music.Singers.Add(singer);
                _music.SaveChanges();
                TempData["Success"] = "Singer Created Successfully";
                return RedirectToAction("Index");
            }
            return View(singer);
        }


        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            SingerTbl? singer = _music.Singers.Find(id);
            if (singer == null)
            {
                return NotFound();
            }
            return View(singer);
        }



        [HttpPost]
        public IActionResult Edit(SingerTbl singers, IFormFile? file1)
        {
            if (ModelState.IsValid)
            {
                string wwwroothpath = _webHostEnvironment.WebRootPath;
                if (file1 != null)
                {
                    string filename = Guid.NewGuid().ToString() + Path.GetExtension(file1.FileName);
                    string imagepath = Path.Combine(wwwroothpath, @"Images/Singer");
                    if (!string.IsNullOrEmpty(singers.ProfilePicture))
                    {
                        var oldImagePath = Path.Combine(wwwroothpath, singers.ProfilePicture.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }
                    using (var filestream = new FileStream(Path.Combine(imagepath, filename), FileMode.Create))
                    {
                        file1.CopyTo(filestream);
                    }
                    singers.ProfilePicture = @"\Images\Singer\" + filename;
                }


                var objFromDb = _music.Singers.FirstOrDefault(u => u.SingerId == singers.SingerId);
                if (objFromDb != null)
                {
                  objFromDb.SingerId = singers.SingerId;
                    objFromDb.SingerName = singers.SingerName;
                    objFromDb.SingerBio = singers.SingerBio;
                    if (singers.ProfilePicture!= null)
                    {
                        objFromDb.ProfilePicture = singers.ProfilePicture;
                    }

                    _music.SaveChanges();
                    TempData["Info"] = "Singer Updated Successfully";

                }

               
                return RedirectToAction("Index");
            }
            return View(singers);
        }

        public IActionResult Delete(int? id)
        {
            SingerTbl? singer = _music.Singers.Find(id);
            if (singer == null)
            {
                return NotFound();
            }
            return View(singer);
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            SingerTbl? singer = _music.Singers.Find(id);
            if (singer == null)
            {
                return NotFound();
            }
            _music.Remove(singer);
            _music.SaveChanges();
            TempData["Error"] = "Singer Deleted Successfully";
            return RedirectToAction("Index");
        }

    }
}

Music-Store/Views/Singer/Create.cshtml
@model SingerTbl
<form method="post" enctype="multipart/form-data">
    <div class="border p-3 mt-4 offset-md-1">
       
        <div class="row pb-2">
            <h2 class=" text-primary">Create Singer</h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="SingerName" class="p-0"></label>
            <input asp-for="SingerName" class="form-control" />
            <span asp-validation-for="SingerName" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="SingerBio" class="p-0"></label>
            <input asp-for="SingerBio" class="form-control" />
            <span asp-validation-for="SingerBio" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="ProfilePicture" class="p-0"></label>
            <input type="file" name="file"  />
            <span asp-validation-for="ProfilePicture" class="text-danger"></span>
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-success form-control">Create</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Singer" asp-action="Index" class="btn btn-secondary">Back</a>
            </div>
        </div>
    </div>
</form>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Music-Store/Views/Singer/Delete.cshtml
@model SingerTbl
<form method="post" enctype="multipart/form-data">
<div class="row">
        <div class="border p-3 mt-4 col-10" >
            <div class="row pb-2">
                <h2 class=" text-primary">Delete Singer</h2>
                <hr />
            </div>

            <div class="mb-3 row p-1">
                <input asp-for="SingerId" hidden />
                <label asp-for="SingerName" class="p-0"></label>
                <input asp-for="SingerName" class="form-control" disabled />

            </div>
            <div class="mb-3 row p-1">
                <input asp-for="SingerId" hidden />
                <label asp-for="SingerBio" class="p-0"></label>
                <input asp-for="SingerBio" class="form-control" disabled />

            </div>
            <div class="mb-3 row p-1">
                <input asp-for="SingerId" hidden />
                <label asp-for="ProfilePicture" class="p-0"></label>
                <input asp-for="ProfilePicture" class="form-control" disabled />

            </div>

            <div class="row">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-danger form-control">Delete</button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="Singer" asp-action="Index" class="btn btn-secondary">Back</a>
                </div>
            </div>
        </div>
    
    <div class="col-2">
            
                <img src="@Model.ProfilePicture" width="100%" style="border-radius:5px; border:1px solid #bbb9b9" />
       
    </div>

</div>
   
</form>

Music-Store/Views/Singer/Edit.cshtml
@model SingerTbl
<form method="post" asp-action="Edit" enctype="multipart/form-data">
    <div class="row">
    <div class="border p-3 mt-4 col-10">
        <div class="row pb-2">
            <h2 class=" text-primary">Update Singer</h2>
            <hr />
        </div>

        <div class="mb-3 row p-1">
            <input asp-for="SingerId" hidden />
            <label asp-for="SingerName" class="p-0"></label>
            <input asp-for="SingerName" class="form-control" />
            <span asp-validation-for="SingerName" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-1">
            <input asp-for="SingerId" hidden />
            <label asp-for="SingerBio" class="p-0"></label>
            <input asp-for="SingerBio" class="form-control" />
            <span asp-validation-for="SingerBio" class="text-danger"></span>
        </div>


         <div class="mb-3 row p-1">
                <input asp-for="SingerId" hidden /> 
                <label asp-for="ProfilePicture" class="p-0"></label>
            <input type="file" name="file1"  accept="image/*" />
            <span asp-validation-for="ProfilePicture" class="text-danger"></span>
        </div>


        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Update</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Singer" asp-action="Index" class="btn btn-secondary">Back</a>
            </div>
        </div>
    </div>
    <div class="col-2">
        <img src="@Model.ProfilePicture" width="100%" style="border-radius:5px; border:1px solid #bbb9b9" />
    </div>
    </div>
</form>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Music-Store/Views/Singer/Index.cshtml
@model List<SingerTbl>

<div class="container">
    <div class="row pt-4 pb-3 offset-md-1">
        <div class="col-6">
            <h2 class="text-primary">Singer List</h2>
        </div>
        <div class="col-6  text-end ">
            <a asp-controller="Singer" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>  Add New Singer
            </a>
        </div>
        <div class="row py-2">
            <table class="table table-borderless table-responsive table-striped">
                <thead>
                    <tr>
                        <th>Profile Picture</th>
                        <th>Singer Title</th>
                        <th>Singer Bio</th>
                        <th></th>
                    </tr>

                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                         <td class="align-middle">
                        <img  src="@item.ProfilePicture"  style="width:100px" height="100"/>
                         </td>
                            <td>@item.SingerName</td>
                            <td>@item.SingerBio</td>
                            <td>
                                <div class="btn btn-group float-end" role="group">
                                    <a asp-controller="Singer" asp-action="Edit" asp-route-id="@item.SingerId" class="btn btn-primary"><i class="bi bi-pencil-square"></i>Edit</a>
                                    <a asp-controller="Singer" asp-action="Delete" asp-route-id="@item.SingerId" class="btn btn-danger">
                                        <i class="bi bi-trash"></i> Delete
                                    </a>
                                </div>
                            </td>

                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>